worldwidefit/urls.py
from django.conf.urls import url
from django.contrib import admin
from worldwidefit_main.views import Home, EventView, EventsView, ResultCreatingView, ContactsView, EventResults, GroupView, GroupEventResultsView, ApproveResultView, GlobalResultCreatingView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='Home'),
    url(r'^event/(?P<pk>[-_\w]+)/$', EventView.as_view(), name='Event'),
    url(r'^events/$', EventsView.as_view(), name='Events'),
    url(r'^contacts/$', ContactsView.as_view(), name='Contacts'),
    url(r'^result/(?P<pk>[-_\w]+)/$', ResultCreatingView.as_view(), name='Result set'),
    url(r'^event/(?P<pk>[-_\w]+)/results/$', EventResults.as_view(), name='EventResults'),
    url(r'^group/(?P<group_pk>[-_\w]+)/event/(?P<event_pk>[-_\w]+)/$', GroupEventResultsView.as_view(), name='GroupEvent'),
    url(r'^group/(?P<pk>[-_\w]+)/$', GroupView.as_view(), name='Group'),
    url(r'^approve/(?P<pk>[-_\w]+)/$', ApproveResultView.as_view(), name='ApproveResult'),
    url(r'^result/$', ResultCreatingView.as_view(), name='ResultSet'),
    url(r'^global/(?P<pk>[-_\w]+)/$', GlobalResultCreatingView.as_view(), name='ResultSet'),
    url(r'^global/$', GlobalResultCreatingView.as_view(), name='ResultSet'),
]

worldwidefit_auth/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from worldwidefit_main.models import Organizer, Event
from django.contrib.auth.models import User


class SportGroup(models.Model):
    title = models.CharField('Название', blank=True, null=False, max_length=255, default='')
    users = models.ManyToManyField(User)
    organizer = models.ForeignKey(Organizer)
    events = models.ManyToManyField(Event)

    class Meta:
        verbose_name = 'Спортивная группа'
        verbose_name_plural = 'Спортивные группы'

    def __unicode__(self):
        return self.title

worldwidefit_main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Organizer(models.Model):
    title = models.CharField('Название', max_length=255, default='')
    description = models.TextField('Подробности', default='', blank=True)
    created = models.DateTimeField('Добавлен', auto_now_add=True)

    class Meta:
        verbose_name = 'Организатор'
        verbose_name_plural = 'Организаторы'

    def __unicode__(self):
        return self.title


class Event(models.Model):
    title = models.CharField('Название', max_length=255, default='')
    description = models.TextField('Подробности', default='', blank=True)
    created = models.DateTimeField('Добавлен', auto_now_add=True)
    ended = models.BooleanField('Уже прошло', blank=False, null=False, default=False)
    isGlobal = models.BooleanField('Глобальное', blank=False, null=False, default=False)

    organizer = models.ForeignKey(Organizer, blank=True, null=True)

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    def __unicode__(self):
        return self.title


class Task(models.Model):
    title = models.CharField('Название', max_length=255, default='')
    description = models.TextField('Подробности', default='', blank=True)
    created = models.DateTimeField('Добавлен', auto_now_add=True)

    event = models.ForeignKey(Event, blank=True, null=True)

    class Meta:
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'

    def __unicode__(self):
        return self.title


class Result(models.Model):
    user = models.ForeignKey(User, blank=False, null=False)
    task = models.ForeignKey(Task, blank=False, null=False)
    result = models.CharField('Результат', max_length=255, blank=False, null=False, default='')
    approved = models.BooleanField('Подтверждён', blank=False, null=False, default=False)
    proof = models.CharField('Подтверждение', max_length=512, blank=True, null=False, default='')

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'
        ordering = ['-result',]

    def __unicode__(self):
        return "{} {} {}".format(self.user.username, self.task.title, self.result)

worldwidefit_main/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from worldwidefit_main.models import Result


class ResultCreatingForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ['result', 'task']
        widgets = {
            'result': forms.TextInput(attrs={'value': '',
                                            'placeholder': "Результат"}),
            'task': forms.HiddenInput(),
        }


class GlobalResultCreatingForm(forms.ModelForm):
    # proof = forms.CharField(widget=forms.TextInput(attrs={'value': '',
    #                                         'placeholder': "Доказательство"}))

    class Meta:
        model = Result
        fields = ['result', 'proof']
        widgets= {
            'proof': forms.TextInput(attrs={'value': '',
                                            'placeholder': "Подтверждение"}),
            'result': forms.TextInput(attrs={'value': '',
                                            'placeholder': "Результат"}),
            'task': forms.HiddenInput(),
        }


class ApproveResultForm(forms.Form):
    result_id = forms.CharField()
    redirect_to = forms.CharField()

worldwidefit_main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import TemplateView, ListView, DetailView, FormView
from worldwidefit_main.models import Event, Task, Result, User
from worldwidefit_auth.models import SportGroup
from worldwidefit_main.forms import ResultCreatingForm, ApproveResultForm, GlobalResultCreatingForm
from django.shortcuts import render_to_response, reverse, redirect
from django.template.context_processors import csrf
import random

class Home(ListView):
    template_name = 'main.html'
    context_object_name = 'events'
    model = Event

    def get_queryset(self):
        return Event.objects.filter(ended=True)


class EventView(DetailView):
    template_name = 'event.html'
    model = Event


class ContactsView(ListView):
    template_name = 'contacts.html'
    def get_queryset(self):
        return Event.objects.filter(ended=True)

class EventsView(ListView):
    template_name = 'events.html'
    context_object_name = 'events'
    model = Event

    def get_queryset(self):
        return Event.objects.filter(ended=False).order_by('-pk')


class EventResults(DetailView):
    template_name = 'results.html'
    model = Event

    def get_context_data(self, **kwargs):
        ctx = super(EventResults, self).get_context_data(**kwargs)
        ctx['events_list'] = Event.objects.filter(ended=False)
        return ctx


class ResultCreatingView(FormView):

    template_name = 'result.html'
    form_class = ResultCreatingForm
    success_url = '/event/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super(ResultCreatingView, self).form_valid(form)

    # В случае get запроса, мы будем отправлять просто страницу с контактной формой
    def get(self, request, *args, **kwargs):
        context = {}
        context.update(csrf(request))  # Обязательно добавьте в шаблон защитный токен

        context['result_form'] = ResultCreatingForm(initial={'task': Task.objects.get(id=self.kwargs['pk']).pk})

        return render_to_response(template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = {}

        form = ResultCreatingForm(request.POST)
        if form.is_valid():

            Result.objects.create(task=Task.objects.get(id=request.POST["task"]),
                                  result=request.POST["result"],
                                  user=request.user)
            task = Task.objects.get(id=request.POST["task"])

            return redirect('{0}{1}/'.format(self.get_success_url(), task.event.pk))
        return render_to_response(template_name=self.template_name, context=context)


class GlobalResultCreatingView(ResultCreatingView):
    form_class = GlobalResultCreatingForm

    def get(self, request, *args, **kwargs):
        context = {}
        context.update(csrf(request))  # Обязательно добавьте в шаблон защитный токен

        context['result_form'] = GlobalResultCreatingForm(initial={'task': Task.objects.get(id=self.kwargs['pk']).pk})

        return render_to_response(template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = {}

        form = ResultCreatingForm(request.POST)
        if form.is_valid():
            result = [" минут", " подходов", " километров", "километров", " минут", " подходов", " подходов",
                      " минут", " километров"]

            # for x in range(1, 8):
            #     for y in range(6, 14):
            #         Result.objects.create(task=Task.objects.get(id=y),
            #                               result='{0}{1}'.format(random.randint(0, 10), result[y - 6]),
            #                               proof=request.POST["proof"],
            #                               user=User.objects.get(id=x))
            Result.objects.create(task=Task.objects.get(id=request.POST["task"]),
                                  result=request.POST["result"],
                                  proof=request.POST["proof"],
                                  user=request.user)
            task = Task.objects.get(id=request.POST["task"])

            return redirect('{0}{1}/'.format(self.get_success_url(), task.event.pk))

class ApproveResultView(FormView):
    form_class = ApproveResultForm
    template_name = 'group_event.html'
    success_url = '/'

    def form_valid(self, form):
        if form.is_valid():

            current_result = Result.objects.get(id=int(form.cleaned_data['result_id']))
            current_result.approved = True
            current_result.save()
            return redirect(form.cleaned_data['redirect_to'])
        else:
            self.form_invalid(form)


class GroupView(DetailView):
    model = SportGroup
    template_name = 'group.html'


class GroupEventResultsView(ListView):
    template_name = 'group_event.html'
    context_object_name = 'results'

    def get_queryset(self):
        sp = SportGroup.objects.get(id=self.kwargs['group_pk'])
        return Result.objects.filter(task__event_id=self.kwargs['event_pk'], user_id__in=sp.users.all().values('id'))

    def get_context_data(self, **kwargs):
        ctx = super(GroupEventResultsView, self).get_context_data(**kwargs)
        ctx['event'] = Event.objects.get(id=self.kwargs['event_pk'])
        ctx['group'] = SportGroup.objects.get(id=self.kwargs['group_pk'])
        return ctx

worldwidefit_main/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Title{% endblock title %} - WorldWideFitness</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/grid_12.css' %}">
    {% block additional_stiles %}
    {% endblock additional_stiles %}
    <script src="{% static 'js/jquery-1.7.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/tms-0.3.js' %}"></script>
	<script src="{% static 'js/tms_presets.js' %}"></script>
    <script src="{% static 'js/cufon-yui.js' %}"></script>
    <script src="{% static 'js/Asap_400.font.js' %}"></script>
    <script src="{% static 'js/Coolvetica_400.font.js' %}"></script>
	<script src="{% static 'js/Kozuka_M_500.font.js' %}"></script>
{#    <script src="{% static 'js/cufon-replace.js' %}"></script>#}
    <script src="{% static 'js/FF-cash.js' %}"></script>
	{% block additional_scripts %}
    {% endblock additional_scripts %}
    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
   		<script type="text/javascript" src="js/html5.js"></script>
    	<link rel="stylesheet" type="text/css" media="screen" href="css/ie.css">
	<![endif]-->
</head>
<body>
<div class="main">
	<div class="bg-img"></div>
<!--==============================header=================================-->
    <header>
        <h1><a href="/">WorldWide <strong>Fitness</strong></a></h1>
        <nav>
        	<div class="social-icons">
            	<a href="#" class="icon-2"></a>
            	<a href="#" class="icon-1"></a>
            </div>
            <ul class="menu">
                <li {% ifequal request.path '/' %}class="current"{% endifequal %}><a href="/">Главная</a></li>
                <li {% ifequal request.path '/events' %}class="current"{% endifequal %}><a href="/events">События</a></li>
{#                <li><a href="timetable.html">Расписание</a></li>#}
{#                <li><a href="nutrition.html">NuTimetabletrition</a></li>#}
{#                <li><a href="gallery.html">Галерея</a></li>#}
                <li {% ifequal request.path '/contacts' %}class="current"{% endifequal %}><a href="/contacts">Контакты</a></li>
            </ul>
        </nav>
    </header>   
<!--==============================content================================-->
    <section id="content">
    {% block content %}
    {% endblock content %}
    </section> 
<!--==============================footer=================================-->
    <footer>
        <p>© 2017 WorldWideFitness</p>
    </footer>
</div>    
<script>
	Cufon.now();
</script>
</body>
</html>

worldwidefit_main/templates/contacts.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Контакты {{ event.title }}{% endblock title %}

{% block content %}
    <section id="content">
        <div class="container_12">
          <div class="grid_12">
          	<div class="box-shadow">
            	<div class="wrap block-2">
                    <div class="col-3">
                    	<h2><span class="color-1">Как найти ?</span></h2>
                        <dl>
                            <dt class="color-1"><strong>Россия ,<br>Пенза, ул. Гагарина 6 440039.</strong></dt>
                            <dd><span>Телефон:</span>+7 996 961 0891</dd>
                            <dd><span>E-mail:</span><a href="#" class="link">vorgovsky@gmail.com</a></dd>
                        </dl>
                    </div>
                    <div class="col-4">
                    	<h2><span class="color-1">Связаться</span> с нами</h2>
                        <form id="form" method="post" >
                            <fieldset>
                              <label><input type="text" value="Имя" onBlur="if(this.value=='') this.value='Имя'" onFocus="if(this.value =='Имя' ) this.value=''"></label>
                              <label><input type="text" value="Email" onBlur="if(this.value=='') this.value='Email'" onFocus="if(this.value =='Email' ) this.value=''"></label>
                              <label><textarea onBlur="if(this.value==''){this.value='Ваше сообщение'}" onFocus="if(this.value=='Ваше сообщение'){this.value=''}">Ваше сообщение</textarea></label>
                              <div class="btns"><a href="#" class="button">Очистить</a><a href="#" class="button" onClick="document.getElementById('form').submit()">Отправить</a></div>
                            </fieldset>
                          </form>
                    </div>
                </div>
            </div>
          </div>
          <div class="Очистить"></div>
        </div>
    </section>
{% endblock content %}

worldwidefit_main/templates/event.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Event {{ event.title }}{% endblock title %}

{% block content %}
    <div class="container_12">
        <div class="grid_12">
            <div class="box-shadow">
                <div class="wrap block-2">
                    <div class="col-3">
                        <h2 class="p3"><span class="color-1">Группы</span></h2>
                        <ul class="list-1">
                            {% for group in event.sportgroup_set.all %}
                                <li><a href="{% url 'GroupEvent' group.pk event.pk %}">{{ group.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-4">
                        <h2 class="p3"><span class="color-1">Событие </span>{{ event.title }}</h2>
                        <p class="p2"><strong>{{ event.description }}</strong></p>
                        {% for task in event.task_set.all %}
                            <div class="wrap box-1 top-4">
                                <img src="{% static 'images/page2-img1.jpg' %}" alt="" class="img-border img-indent">
                                <div class="extra-wrap">
                                    <p class="p2"><strong>{{ task.title }}</strong></p>
                                    <p>{{ task.description }}</p>
                                    {% if not user.is_anonymous %}
                                        {% if task.result_set.all.count == 0 %}
                                            <div class="form-result">
                                                <form action="{% if not event.isGlobal %}/result/{% else %}/global/{% endif %}" method="post" class="form-{{ task.pk }}" id="form">
                                                    {% csrf_token %}
                                                    <fieldset>
                                                        <div class="fieldWrapper">
                                                            <label><input name="result" value="" required="" placeholder="Результат" id="id_result" maxlength="255" type="text"></label>
                                                        </div>
                                                        {% if event.isGlobal %}
                                                            <div class="fieldWrapper">
                                                                <label><input name="proof" required="" maxlength="512" value="" placeholder="Подтверждение" id="id_proof" type="text"></label>
                                                            </div>
                                                        {% endif  %}
                                                        <div class="fieldWrapper">
                                                            <label><input name="task" value="{{ task.pk }}" id="id_task" type="hidden"></label>
                                                        </div>
                                                    </fieldset>
                                                    <div class="btns"><a href="#" class="button" onClick="document.getElementsByClassName('form-{{ task.pk }}')[0].submit()">Отправить</a></div>
                                                </form>
                                            </div>
                                        {% elif task.result_set.first.approved %}
                                            <div class="form-result">
                                                <div class="aprovedMessage">
                                                    Ваш результат подтверждён
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="form-result">
                                                <div class="infoMessage">
                                                    Ваш результат принят
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% else %}
                                        <p class="margin_top_10"><strong><a href="#">Войдите</a> или <a href="#">зарегистрируйтесь</a></strong></p>
                                    {% endif %}

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
{% endblock content %}

worldwidefit_main/templates/group.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Мероприятие{% endblock title %}

{% block content %}
        <div class="container_12">
          <div class="grid_12">
          	<div class="box-shadow">
            	<div class="wrap block-2">
                    <div class="col-1">
                    	<h2 class="p3"><span class="color-1">Лучшие в мероприятии: {{ event.title }}</span></h2>

                        <div class="wrap box-2 border-1">
                            {% for user in sportgroup.users.all %}
                            <div>
                            	<p><strong>{{ user.get_full_name }}: </strong></p>
{#                                <p class="color-1">{{ task.result_set.first.result }}</p>#}
{#                                <a href="{% url 'ApproveResult' task.result_set.first.result.id %}" class="button top-5">Подтвердить</a>#}
{#                                <p>{{ task.result_set.first.user.get_full_name }}</p>#}
                            </div>
                            {% endfor %}
                        </div>
{#                        <div class="wrap box-2 border-1">#}
{#                            <div>#}
{#                                <p class="color-1">12:00</p>#}
{#                                <p>Consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.</p>#}
{#                            </div>#}
{#                            <div>#}
{#                                <p class="color-1">12:30</p>#}
{#                                <p>Magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>#}
{#                            </div>#}
{#                            <div class="last">#}
{#                                <p class="color-1">11:00</p>#}
{#                                <p>Vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit.</p>#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                    <div class="col-2">
                        <h2 class="p3"><span class="color-1">Предстоящие</span> Мероприятия</h2>
                        <p class="p2"><strong>Откытые мероприятия: </strong></p>
{#                        <p>Option congue nihil imperdiet doming id quod mazim placerat facer possim assum:</p>#}
                        <img src="{% static 'images/page3-img1.jpg' %}" alt="" class="img-border pad-1">
                        <ul class="list-2">
                            {% for event in events_list %}
                        	<li><a href="{% url 'Event' event.id %}">{{ event.title }}</a></li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'Events' %}" class="button top-5">Посмотреть все</a>
                    </div>
                </div>
            </div>
          </div>
          <div class="clear"></div>
        </div>
{% endblock content %}

worldwidefit_main/templates/result.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Main{% endblock title %}

{% block additional_stiles %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/slider.css' %}">
{% endblock additional_stiles %}

{% block additional_scripts %}
    <script>
        $(window).load(function(){
            $('.slider')._TMS({
                prevBu:'.prev',
                nextBu:'.next',
                pauseOnHover:true,
                pagNums:false,
                duration:800,
                easing:'easeOutQuad',
                preset:'Fade',
                slideshow:7000,
                pagination:'.pagination',
                waitBannerAnimation:false,
                banners:'fade'
            })
        })
    </script>
{% endblock additional_scripts %}

{% block content %}

    <div class="container_12">
        <div class="grid_12">
            <div class="form-result">
                <form action="/result/" method="post" id="form">
                    {% csrf_token %}

                    <fieldset>
{#                    <div class="fieldWrapper">#}
{#                        <input type="hidden" name="task" value="{{ task.id }}">#}
{#                        <label><input name="result" value="" required="" id="id_result" placeholder="Результат" type="text"></label>#}
{#                    </div>#}
                    {% for field in result_form %}
                        <div class="fieldWrapper">
                            {{ field.errors }}
                            <label>{{ field }}</label>
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </fieldset>
                    <div class="btns"><a href="#" class="button" onClick="document.getElementById('form').submit()">Отправить</a></div>
                </form>
            </div>


        </div>
        <div class="clear"></div>
    </div>
{% endblock content %}

worldwidefit_main/templates/results.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Мероприятие{% endblock title %}

{% block content %}
        <div class="container_12">
          <div class="grid_12">
          	<div class="box-shadow">
            	<div class="wrap block-2">
                    <div class="col-1">
                    	<h2 class="p3"><span class="color-1">Лучшие в мероприятии: {{ event.title }}</span></h2>

                        <div class="wrap box-2 border-1">
                            {% for task in event.task_set.all %}
                            <div>
                            	<p><strong>{{ task.title }}: </strong></p>
                                <p class="color-1">{{ task.result_set.first.result }}</p>
                                <p>{{ task.result_set.first.user.get_full_name }}</p>
                            </div>
                            {% endfor %}
{#                            <div>#}
{#                            	<p><strong>Wednesday</strong></p>#}
{#                                <p class="color-1">10:00</p>#}
{#                                <p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore.</p>#}
{#                            </div>#}
{#                            <div class="last">#}
{#                            	<p><strong>Friday</strong></p>#}
{#                                <p class="color-1">9:30</p>#}
{#                                <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>#}
{#                            </div>#}
                        </div>
{#                        <div class="wrap box-2 border-1">#}
{#                            <div>#}
{#                                <p class="color-1">12:00</p>#}
{#                                <p>Consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.</p>#}
{#                            </div>#}
{#                            <div>#}
{#                                <p class="color-1">12:30</p>#}
{#                                <p>Magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>#}
{#                            </div>#}
{#                            <div class="last">#}
{#                                <p class="color-1">11:00</p>#}
{#                                <p>Vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit.</p>#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                    <div class="col-2">
                        <h2 class="p3"><span class="color-1">Предстоящие</span> Мероприятия</h2>
                        <p class="p2"><strong>Откытые мероприятия: </strong></p>
{#                        <p>Option congue nihil imperdiet doming id quod mazim placerat facer possim assum:</p>#}
                        <img src="{% static 'images/page3-img1.jpg' %}" alt="" class="img-border pad-1">
                        <ul class="list-2">
                            {% for event in events_list %}
                        	<li><a href="{% url 'Event' event.id %}">{{ event.title }}</a></li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'Events' %}" class="button top-5">Посмотреть все</a>
                    </div>
                </div>
            </div>
          </div>
          <div class="clear"></div>
        </div>
{% endblock content %}